# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('categoryName', 'categoryID'),
            },
        ),
        migrations.CreateModel(
            name='Dagr',
            fields=[
                ('Guid', models.AutoField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=300)),
                ('RealName', models.CharField(max_length=200)),
                ('AssignedName', models.CharField(max_length=200)),
                ('LastModified', models.DateTimeField()),
                ('DateCreated', models.DateTimeField()),
                ('Size', models.DecimalField(decimal_places=4, max_digits=20)),
                ('Type', models.CharField(max_length=20)),
                ('Author', models.CharField(default='N/A', max_length=200)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dagrs', to='dagr.Category')),
            ],
            options={
                'ordering': ('AssignedName', 'Type', 'Author'),
            },
        ),
        migrations.CreateModel(
            name='Dagr_keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='dagr.Dagr')),
            ],
            options={
                'ordering': ('keyword',),
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keywordID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParentGUID', models.IntegerField()),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('ChildGUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dagr.Dagr')),
            ],
            options={
                'ordering': ('ParentGUID',),
            },
        ),
        migrations.AddField(
            model_name='dagr_keywords',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dagrs', to='dagr.Keyword'),
        ),
        migrations.AlterUniqueTogether(
            name='relationships',
            unique_together=set([('ParentGUID', 'ChildGUID')]),
        ),
    ]
