# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dagr',
            name='AssignedName',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='dagr',
            name='Type',
            field=models.CharField(max_length=300),
        ),
    ]
